
name: Gradle Java Toolchains

on: workflow_dispatch

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    name: Tool chains - ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: |
            17
            8
      - name: Show environment
        run: env
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: List Java toolchains
        run: ./gradlew --show-version javaToolchains
